# Ejecutivo Express.js server
# ----------------------------------------------
FROM node:20-alpine

WORKDIR /usr/src/app
COPY package.json ./
RUN npm install --only=production
COPY . .

EXPOSE 8080

CMD ["node", "app.js"]